import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import styles from '@styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href={'/login'}><button className={styles.login}>Login</button></Link>
        <Link href={'/register'}><button className={styles.register}>Register</button></Link>
        <Link href={'/dashboard'}><button className={styles.link}>Dashboard</button></Link>
      </main>
    </div>
  )
}

export default Home
